[project]
name = "11-connect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ruff>=0.9.9",
    "sqlalchemy>=2.0.38",
    "streamlit>=1.42.2",
]
